# Generated by Django 4.1.1 on 2022-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=100, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, default=10, editable=False, max_digits=10),
        ),
    ]
