# Generated by Django 4.1.1 on 2022-11-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Basic', 'Basic Plan'), ('Gold', 'Gold Plan'), ('Platinum', 'Platinum Plan')], max_length=8)),
                ('percent', models.PositiveIntegerField()),
                ('ref_bonus', models.PositiveIntegerField(default=10)),
                ('min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calc_percent', models.DecimalField(decimal_places=2, default=100.0, editable=False, max_digits=10, verbose_name='Percentage Formula')),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Btc', 'Bitcoin - BTC'), ('Eth', 'Ethereum - ETH'), ('Trc20', 'Tether - USDT(TRC20)')], default='Btc', max_length=20, verbose_name='Wallet name')),
                ('address', models.CharField(max_length=60, verbose_name='Wallet address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wallet Address',
                'unique_together': {('user', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Withdrawal', editable=False, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000, verbose_name='Withdrawal amount')),
                ('min_withdraw', models.DecimalField(decimal_places=2, default=80.0, max_digits=1000, verbose_name='Minimum withdrawal')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=12, verbose_name='Withdrawal status')),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('initiated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(default='Btc', on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.wallet', verbose_name='Withdrawal wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Deposit', editable=False, max_length=10)),
                ('sub_method', models.CharField(choices=[('Account', 'Account Balance'), ('Wallet', 'Wallet')], default='Account', max_length=24)),
                ('sub_currency', models.CharField(choices=[('Btc', 'Bitcoin - BTC'), ('Eth', 'Ethereum - ETH'), ('Trc20', 'Tether - USDT(TRC20)')], default='Btc', max_length=12)),
                ('sub_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Expired', 'Expired')], default='Pending', max_length=9)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('initiated_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan', to='dashboard.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
