# Generated by Django 4.1.1 on 2022-11-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_withdrawal_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('Btc', 'Bitcoin - BTC'), ('Eth', 'Ethereum - ETH'), ('Trc20', 'Tether - USDT(TRC20)')], max_length=20, verbose_name='Wallet name'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.wallet', verbose_name='Withdrawal wallet'),
        ),
    ]
